version: '3'
networks:
  monitoring:
    driver: bridge
volumes:
    prometheus_data: {}
    loki-data: {}
    grafana_data: {}

services:

  diag-service:
    image: diag-service:v1.0.0
    build:
      context: diag-service
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - monitoring

  # Loki
  loki:
    image: grafana/loki:2.5.0
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - --config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml:ro
    networks:
      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:8.5.0
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes: 
      - ./grafana/provisioning-datasources.yml:/etc/grafana/provisioning/datasources/provisioning-datasources.yml
    networks:
      - monitoring
