name: build_and_deploy_lightsail
on: push

env:
  NODE_ENV: "dev"
  SERVICE_NAME: "diag-service"

jobs:
  run-services:
    runs-on: ubuntu-latest
    services:
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: prereqs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION
          aws configure set region $AWS_DEFAULT_REGION
      - name: Install essentials
        run: |
          aws --version
          # install LightsailCTL Plugin (https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-install-software)
          sudo apt-get update && sudo apt-get -y install curl jq
          curl https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl -o /usr/local/bin/lightsailctl
          chmod +x /usr/local/bin/lightsailctl
      - name: Release to Lightsail
        run: |
          echo "Releasing to Amazon Lightsail"
          docker info

          # upload the docker image for this pipeline
          aws lightsail push-container-image \
            --service-name diag-service \
            --label  diag-service \
            --image diag-service:v1.0.0

          aws lightsail push-container-image \
            --service-name prometheus \
            --label prometheus \
            --image prom/prometheus:v2.35.0

          aws lightsail push-container-image \
            --service-name loki \
            --label loki  \
            --image grafana/loki:2.5.0

          aws lightsail push-container-image \
            --service-name grafana \
            --label grafana \
            --image grafana/grafana:8.5.0

          # get uploaded image (its different every time)
          SERVICE_IMAGE_TAG=$(aws lightsail get-container-images --service-name diag-service | jq -r .containerImages[0].image)
          PROMETHEUS_IMAGE_TAG=$(aws lightsail get-container-images --service-name prometheus | jq -r .containerImages[0].image)
          LOKI_IMAGE_TAG=$(aws lightsail get-container-images --service-name loki | jq -r .containerImages[0].image)
          GRAFANA_IMAGE_TAG=$(aws lightsail get-container-images --service-name grafana | jq -r .containerImages[0].image)

          # create a deployment with uploaded docker image
          aws lightsail create-container-service-deployment \
            --service-name diag-service \
            --containers "{
              \"diag-service\": {
                \"image\": \"$SERVICE_IMAGE_TAG\",
                \"ports\": {
                  \"8000\": \"HTTP\"
                }
              },
              \"prometheus\": {
                \"image\": \"$PROMETHEUS_IMAGE_TAG\",
                \"ports\": {
                  \"9090\": \"HTTP\"
                }
              },
              \"loki\": {
                \"image\": \"$LOKI_IMAGE_TAG\",
                \"ports\": {
                  \"3100\": \"HTTP\"
                }
              },
              \"grafana\": {
                \"image\": \"$GRAFANA_IMAGE_TAG\",
                \"ports\": {
                  \"3000\": \"HTTP\"
                }
              }
            }" \
            --public-endpoint "{
              \"containerName\": \"diag-service\",
              \"containerPort\": 8000
            }"